import Navbar from '@/components/navbar'
import './globals.css'
import ScrollToTop from '@/components/scroll-to-top'
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: 'Car Next Js',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative'>
        <NextTopLoader 
          color='#2299DD'
          height={3}
          speed={500}
          showSpinner={false}
        />
        <ScrollToTop />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
